# Generated by Django 4.1.7 on 2023-03-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_route_userprofiledetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersAddressDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=30)),
                ('door_no', models.CharField(blank=True, max_length=25)),
                ('street_name', models.CharField(blank=True, max_length=25)),
                ('village_name', models.CharField(blank=True, max_length=25)),
                ('city_name', models.CharField(blank=True, max_length=20)),
                ('district_name', models.CharField(blank=True, max_length=20)),
                ('state_name', models.CharField(blank=True, max_length=20)),
                ('pincode', models.CharField(blank=True, max_length=8)),
                ('mobile_no', models.IntegerField(blank=True, max_length=13)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
