# Generated by Django 4.1.7 on 2023-03-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_usersaddressdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersaddressdetails',
            name='mobile_no',
            field=models.IntegerField(blank=True),
        ),
    ]
