# Generated by Django 4.1.7 on 2023-03-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_usersaddressdetails_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersaddressdetails',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
