# Generated by Django 4.1.7 on 2023-03-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_usersaddressdetails_mobile_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.FileField(max_length=1000, upload_to='Banner_image/')),
                ('description', models.CharField(blank=True, max_length=25)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
