# Generated by Django 4.1.7 on 2023-03-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_bannerupdate_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerupdate',
            name='status',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='bannerupdate',
            name='location',
            field=models.ImageField(max_length=1000, upload_to='Media'),
        ),
    ]
