# Generated by Django 4.1.7 on 2023-03-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_bannerupdate_status_alter_bannerupdate_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ImageField(max_length=1000, upload_to='Product')),
                ('offer', models.CharField(blank=True, max_length=25)),
                ('price', models.CharField(blank=True, max_length=256)),
                ('discount', models.CharField(blank=True, max_length=25)),
                ('product_name', models.CharField(blank=True, max_length=256)),
                ('product_description', models.CharField(blank=True, max_length=25)),
                ('post_type', models.CharField(blank=True, max_length=25)),
                ('status', models.CharField(blank=True, max_length=256)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bannerupdate',
            name='location',
            field=models.ImageField(max_length=1000, upload_to='Banner'),
        ),
    ]
