# Generated by Django 4.1.7 on 2023-03-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productupdate_alter_bannerupdate_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerupdate',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='productupdate',
            name='product_description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='usersaddressdetails',
            name='city_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='usersaddressdetails',
            name='district_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='usersaddressdetails',
            name='door_no',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='usersaddressdetails',
            name='pincode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='usersaddressdetails',
            name='state_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='usersaddressdetails',
            name='street_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='usersaddressdetails',
            name='village_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
