# Generated by Django 4.1.7 on 2023-03-25 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_bannerupdate_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCartUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=30)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addcartupdate', to='products.productupdate')),
            ],
        ),
    ]
