# Generated by Django 4.1.7 on 2023-04-14 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_reviewupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewUpdate',
        ),
    ]
