# Generated by Django 4.1.7 on 2023-04-14 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_delete_reviewupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=250)),
                ('customer_review', models.CharField(blank=True, max_length=256)),
                ('client_review', models.CharField(blank=True, max_length=25)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewupdate', to='products.productupdate')),
            ],
        ),
    ]
