# Generated by Django 4.1.7 on 2023-04-14 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_reviewupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewUpdate',
        ),
    ]
