# Generated by Django 4.1.7 on 2023-04-15 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_reviewupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=250)),
                ('user_email', models.EmailField(max_length=30)),
                ('customer_rate', models.CharField(blank=True, max_length=256)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateupdate', to='products.productupdate')),
            ],
        ),
    ]
