# Generated by Django 4.1.7 on 2023-04-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_rateupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='productupdate',
            name='customer_rate',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
