# Generated by Django 4.1.7 on 2023-05-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_productupdate_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productupdate',
            name='shipping_mode',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
