# Generated by Django 4.1.7 on 2023-05-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='roleStatus',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
