# Generated by Django 4.1.7 on 2023-05-22 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_customuser_rolestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternate_number', models.CharField(blank=True, max_length=13)),
                ('payment_method', models.CharField(blank=True, max_length=250)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('doorNo', models.CharField(blank=True, max_length=250)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(blank=True, max_length=256)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderdelivery', to='products.productupdate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderdelivery', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
