# Generated by Django 4.1.7 on 2023-05-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_productsupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsupdate',
            name='process_status',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
