# Generated by Django 4.1.7 on 2023-05-28 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_addcartupdate_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewupdate',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewupdate', to='products.productsupdate'),
        ),
    ]
