# Generated by Django 4.1.7 on 2023-05-31 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_reviewupdate_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsupdate',
            name='category_type',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='productsupdate',
            name='product_type',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.CreateModel(
            name='CategoryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=250)),
                ('status', models.CharField(blank=True, max_length=256)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorylist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
