# Generated by Django 4.1.7 on 2023-06-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_productsupdate_category_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorylist',
            name='sub_category',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
