# Generated by Django 4.2.4 on 2023-08-02 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_alter_recentvisit_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RateUpdate',
        ),
    ]
