# Generated by Django 4.2.4 on 2023-08-02 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_delete_categorylist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewUpdate',
        ),
    ]
