# Generated by Django 4.2.4 on 2023-08-02 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_delete_reviewupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDelivery',
        ),
    ]
