# Generated by Django 4.2.4 on 2023-08-02 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_delete_recentvisit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddCartUpdate',
        ),
    ]
