# Generated by Django 4.2.4 on 2023-08-02 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_delete_addcartupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductUpdate',
        ),
    ]
