# Generated by Django 4.2.4 on 2023-08-02 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_delete_productupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Route',
        ),
    ]
