# Generated by Django 4.2.4 on 2023-08-02 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_delete_productsupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerUpdate',
        ),
    ]
