# Generated by Django 4.2.4 on 2023-08-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_delete_bannerupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='floaterId',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='customuser',
            name='runnerId',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
