# Generated by Django 4.2.4 on 2023-08-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_floaterunitdetails_runnerunitdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewerDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceId', models.CharField(blank=True, max_length=256)),
                ('runnerUnit_limit_switch', models.CharField(blank=True, max_length=256)),
                ('runnerUnitRelay_1', models.CharField(blank=True, max_length=256)),
                ('runnerUnitRelay_2', models.CharField(blank=True, max_length=256)),
                ('runnerUnitRelay_3', models.CharField(blank=True, max_length=256)),
                ('runnerUnitDistance', models.CharField(blank=True, max_length=256)),
                ('floaterUnit_limit_switch', models.CharField(blank=True, max_length=256)),
                ('floaterUnitRelay_1', models.CharField(blank=True, max_length=256)),
                ('floaterUnitRelay_2', models.CharField(blank=True, max_length=256)),
                ('floaterUnitRelay_3', models.CharField(blank=True, max_length=256)),
                ('floaterUnitDistance', models.CharField(blank=True, max_length=256)),
                ('status', models.CharField(blank=True, max_length=256)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UsersAddressDetails',
        ),
    ]
