# Generated by Django 4.2.4 on 2023-08-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_viewerdevice_delete_usersaddressdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewerdevice',
            name='error',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
