# Generated by Django 4.2.4 on 2023-08-22 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_reportupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportUpdate',
        ),
    ]
