# Generated by Django 4.2.4 on 2023-08-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_delete_reportupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(blank=True, max_length=256)),
                ('description', models.CharField(blank=True, max_length=550)),
                ('location', models.FileField(max_length=1000, upload_to='Report')),
                ('status', models.CharField(blank=True, max_length=256)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
