# Generated by Django 4.2.4 on 2023-08-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0051_catalogdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogdetails',
            name='user_email',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
