# Generated by Django 4.2.4 on 2023-08-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0052_catalogdetails_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewerdevice',
            name='notification',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
